### ISSUE TITLE
Failed to copy DCE file

### ISSUE THREAD

**Issue by lagnajeet** [ShiftMediaProject/FFVS-Project-Generator#10] opened 2017-08-17 00:33 UTC
I get the following error.
Error: Failed to copy dce file (libavcodec/x86/flacdsp_init.c) to temporary directory (FFVSTemp/libavcodec/libavcodec/x86/flacdsp_init.c)

I used FFMpeg from your GitHub and from ffmpeg's github but in both the cases I get the same error. I have also tried running the program in admin mode but that also didn't work. Here are my system specs 

Windows 10 x64
Both Visual studio 2015 and 2017
Intel compiler 17 update 2
GCC 7 x64
No YASM

**Comment by Dan203** [comment] 2017-08-17 19:36
Be careful about your path. I discovered that the program doesn't work if any of the folders in your path contain spaces.

**Comment by Sibras** [comment] 2017-08-18 09:19
What command line arguments are you using as ill need those to help identity the problem.

**Comment by lagnajeet** [comment] 2017-08-18 10:24
Below is the command line argument.

--enable-gpl --enable-version3 --disable-avisynth --disable-nonfree --disable-bzlib --disable-iconv --disable-zlib --disable-libmp3lame --disable-libvorbis --disable-libspeex --disable-libopus --disable-libfdk-aac --disable-libtheora    --disable-libx264 --disable-libxvid --disable-libvpx --disable-libmodplug   --disable-libsoxr --disable-libfreetype --disable-fontconfig    --disable-libass --disable-openssl --disable-librtmp --disable-libssh --disable-zlib --disable-lzma --disable-sdl --disable-ffprobe --toolchain=icl

**Comment by Sibras** [comment] 2017-08-18 10:55
OK i have tested the above command line using the current version of FFVS and could not reproduce any issues. As per Dan203s comment i also tested it where the parent directory had spaces in the name and it still worked without issue.

What is the complete folder path you are running FFVS from and what is the complete path for the ffmpeg source code directory?

**Comment by lagnajeet** [comment] 2017-08-18 19:26
F:\dev\ffvs\FFmpegSrc>..\project_generate.exe --enable-gpl --enable-version3 --disable-avisynth --disable-nonfree --disable-bzlib --disable-iconv --disable-zlib --disable-libmp3lame --disable-libvorbis --disable-libspeex --disable-libopus --disable-libfdk-aac --disable-libtheora    --disable-libx264 --disable-libxvid --disable-libvpx --disable-libmodplug   --disable-libsoxr --disable-libfreetype --disable-fontconfig    --disable-libass --disable-openssl --disable-librtmp --disable-libssh --disable-zlib --disable-lzma --disable-sdl --disable-ffprobe --toolchain=icl
Project generator (this may take several minutes, please wait)...
  Passing configure file...
  Outputting config.h...
  Outputting avconfig.h...
  Outputting ffversion.h...
  Outputting enabled components file libavcodec/bsf_list.c...
  Outputting enabled components file libavformat/protocol_list.c...
  Generating from Makefile (./libavcodec/)...
  Generating from Makefile (./libavcodec/x86/)...
  Generating missing DCE symbols (libavcodec)...
  Error: Failed to copy dce file (libavcodec/x86/flacdsp_init.c) to temporary directory (FFVSTemp/libavcodec/libavcodec/x86/flacdsp_init.c)
Press any key to continue . . .

**Comment by Sibras** [comment] 2017-08-19 03:50
OK i can see the potential issue here. Its most likely due to you executing FFVS in a different current working directory to where it is actually located (i.e. the '..\' bit). Ill look into making a fix for this.

In the mean time though you should be able to run the current version just do so by executing it from "F:\dev\ffvs" instead. Then rename "FFmpegSrc" to just "FFmpeg" so that FFVS finds the code directory (or if you don't want to rename FFmpegSrc then you can tell FFVS where the source code is by adding --rootdir=FFmpegSrc to the command line).

**Closed** 2017-08-20 12:19 UTC

**Comment by Sibras** [comment] 2017-08-20 12:20
Should be fixed now in the latest version.
